### ISSUE TITLE
Could you update for v3 links?

### ISSUE THREAD

**Issue by YungSamzy** [open-antux/random-onion-link#1]
hey! I'm just wondering if you could update the generator to support v3 onion links as v2 will be deprecated in december!

**Comment by open-antux** [comment]
Of course, in these days I will update the generator👍

Il giorno ven 2 apr 2021 alle ore 04:09 Simp ***@***.***> ha
scritto:

**Comment by YungSamzy** [comment]
Thanks!

**Comment by open-antux** [comment]
Check the latest [commit](https://github.com/open-antux/random-onion-link/commit/c02e62e79210a3740797375c29f60e536e912e22) 👍
